trigger:
  branches:
    include:
      - main  # or whichever branch you want to trigger on

jobs:
- job: RunPowerShellScript
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: 'track_build_create-bug.ps1'
      arguments: '-organization $(organization) -project $(project) -pipelineId $(pipelineId) -pat $(pat)'
